parameters:
    wizin_simple_cms.service.template.class: "Wizin\Bundle\SimpleCmsBundle\Service\Template"
    wizin_simple_cms.left_delimiter: "<{"
    wizin_simple_cms.right_delimiter: "}>"
    wizin_simple_cms.template_dir: ~
    wizin_simple_cms.template_extension: "twig"
    wizin_simple_cms.base_url: ~
