parameters:
    wizin_simple_cms.service.template.class: "Wizin\Bundle\SimpleCmsBundle\Service\Template"
    wizin_simple_cms.service.content_manager.class: "Wizin\Bundle\SimpleCmsBundle\Service\ContentManager"
    wizin_simple_cms.event.filter_controller_listener.class: "Wizin\Bundle\SimpleCmsBundle\Event\FilterControllerListener"
    wizin_simple_cms.left_delimiter: "<{"
    wizin_simple_cms.right_delimiter: "}>"
    wizin_simple_cms.template_dir: ~
    wizin_simple_cms.template_extension: "twig"
    wizin_simple_cms.base_url: ~
