services:
    wizin_simple_cms.template:
        class: "%wizin_simple_cms.service.template.class%"
        calls:
            - [setContainer, ["@service_container"]]
            - [setTemplateDir, ["%wizin_simple_cms.template_dir%"]]

    wizin_simple_cms.content_manager:
        class: "%wizin_simple_cms.service.content_manager.class%"
        calls:
            - [setContainer, ["@service_container"]]

    wizin_simple_cms.event.filter_controller_listener:
        class: "%wizin_simple_cms.event.filter_controller_listener.class%"
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

